### ISSUE TITLE
spark 7111 enigma2 error

### ISSUE THREAD

**Issue by audi06** [PLi-metas/meta-fulan#2]
Hi
spark 7111 enigma2 error
/usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x462CD8]

> Taapat based on OpenPLi Enigma2 crash log
> 
> crashdate=Sat Jan 1 01:03:18 2000
> compiledate=Aug 11 2018
> skin=Default Skin
> sourcedate=2018-08-08
> branch=develop
> rev=902c51f
> component=enigma2, signal
> 
> stbmodel=spark
> kernelcmdline=console=ttyAS0,115200 root=/dev/mtdblock6 rw rootfstype=jffs2 init=/bin/devinit coprocessor_mem=4m@0x40000000,4m@0x40400000 printk=1 stmmaceth=ethaddr:24:00:10:00:01:1E
> nimsockets=NIM Socket 0:
> imageversion=openpli pli-extras \n \l
> imageissue=openpli pli-extras %h
> 
> Backtrace:
> /usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x462CD8]
> -------FATAL SIGNAL
> 
> dmesg
> 
> VFD/AOTOM: unknown IOCTL 0x1015
> stv090x_init: AGCRF1CFG = 0x10
> stv090x_init: AGCRF2CFG = 0x13
> msg.addr = 96
> config->addr = 96
> ix7306_write: write error, err=-121
> nim_vz7306_control: I2C write error init_data1
> reset_tsm: 1 numRunningFeeds: 0 => calling stm_tsm_init(1)
> [Spark] reinit stream routing...
> start dmx 88cab384, sh 2, pid 0, t 0, pt 1
> ret slothandle = 20000
> SlotHandle = 20000
> linking slot 20000 to descrambler 1, session = 2 type=1
> pti_hal_slot_set_pid: 2 20000 0
> pti_hal_slot_set_pid ok (pid 0, tc = 0)
> stop sh 2, pid 0, pt 1
> Reference = 0
> pti_hal_slot_clear_pid slot = 0, tc = 0, num = 1
> pti_hal_slot_free 20000
> reset_tsm: 1 numRunningFeeds: 0 => calling stm_tsm_init(1)
> [Spark] reinit stream routing...
> start dmx 88cab904, sh 1, pid 0, t 0, pt 1
> ret slothandle = 20000
> SlotHandle = 20000
> linking slot 20000 to descrambler 1, session = 1 type=1
> pti_hal_slot_set_pid: 1 20000 0
> pti_hal_slot_set_pid ok (pid 0, tc = 0)
> stop sh 1, pid 0, pt 1
> Reference = 0
> pti_hal_slot_clear_pid slot = 0, tc = 0, num = 1
> pti_hal_slot_free 20000
> proc_vmpeg_0_dst_left_write 9 - 00000000
> 
> get output window to 0 0 1280, 720 ok
> set output window ok 0 0 1280 720
> proc_vmpeg_0_dst_top_write 9 - 00000000
> 
> get output window to 0 0 1280, 720 ok
> set output window ok 0 0 1280 720
> proc_vmpeg_0_dst_width_write 9 - 00000000
> 
> get output window to 0 0 1280, 720 ok
> set output window ok 0 0 0 720
> proc_vmpeg_0_dst_height_write 9 - 00000000
> 
> get output window to 0 0 0, 720 ok
> set output window ok 0 0 0 0
> proc_vmpeg_0_dst_left_write 9 - 00000000
> 
> failed to get output window -22
> failed to set output window -22
> proc_vmpeg_0_dst_top_write 9 - 00000000
> 
> failed to get output window -22
> failed to set output window -22
> proc_vmpeg_0_dst_width_write 9 - 00000000
> 
> failed to get output window -22
> failed to set output window -22
> proc_vmpeg_0_dst_height_write 9 - 00000000
> 
> failed to get output window -22
> failed to set output window -22
> proc_video_videomode_preferred_read
> proc_video_videomode_preferred_read
> proc_video_videomode_preferred_read
> proc_audio_ac3_choices_read 1024
> proc_audio_ac3_choices_read 1004
> proc_audio_ac3_choices_read 1024
> aotom_write_rtc_offset 4 - aotom_write_rtc_offset -> 3600
>  offset: 3600
> proc_video_policy_choices_read
> proc_video_policy_choices_read
> proc_video_policy_choices_read
> proc_video_policy_choices_read
> proc_video_policy_choices_read
> proc_video_policy_choices_read
> proc_video_policy_choices_read
> proc_video_policy_choices_read
> proc_video_policy_choices_read
> proc_avs_0_colorformat_write 4 - cvbs
> proc_video_aspect_write 3 - 88cab088, 88cab000, 1, 88019180any
> proc_video_policy_write 7 - bestfit
> proc_denc_0_wss_write 4 - auto
> proc_avs_0_input_write 7 - encoder
> proc_avs_0_input_choices_read
> proc_avs_0_input_choices_read
> proc_audio_ac3_write 7 - downmix
> proc_video_alpha_write 3 - 255
> proc_hdmi_audio_source_write 3 - pcm
> stmhdmiio_set_audio_source - 88d20000
> proc_audio_j1_mute_write 1 - 0
> power_standbyled_write(2, ononproc_misc_12V_output_write 3
> proc_hdmi_edid_handling_write 9 - nonstrict
> stmhdmiio_set_edid_handling - 88d20000
> proc_video_hdmi_colorspace_write 8 - hdmi_rgb
> proc_video_videomode_choices_read 1024
> proc_video_videomode_choices_read 790
> proc_video_videomode_choices_read 1024
> three_d_mode_write 3 - off
> proc_avs_0_colorformat_write 8 - hdmi_rgb
> proc_avs_0_colorformat_write 3 - yuv
> proc_hdmi_audio_source_write 3 - pcm
> stmhdmiio_set_audio_source - 88d20000
> proc_video_aspect_write 3 - 88cab088, 88cab000, 1, 88019180any
> proc_video_policy_write 7 - bestfit
> proc_denc_0_wss_write 4 - auto
> proc_video_aspect_write 3 - 88cab088, 88cab000, 1, 88019180any
> proc_video_policy_write 7 - bestfit
> proc_denc_0_wss_write 4 - auto
> proc_video_aspect_write 3 - 88cab088, 88cab000, 1, 88019180any
> proc_video_policy_write 7 - bestfit
> proc_denc_0_wss_write 4 - auto
> proc_video_aspect_write 3 - 88cab088, 88cab000, 1, 88019180any
> proc_video_policy_write 7 - bestfit
> proc_denc_0_wss_write 4 - auto
> proc_video_videomode_write 6 - 720p50
> Found mode to set 720p50 at 21
> proc_video_videomode_write 6 - 720p50
> Found mode to set 720p50 at 21
> proc_video_aspect_write 3 - 88cab088, 88cab000, 1, 88019180any
> proc_video_policy_write 7 - bestfit
> proc_denc_0_wss_write 4 - auto
> proc_avs_0_colorformat_write 3 - yuv

**Comment by MastaG** [comment]
I caused this..
Will fix it next week

**Comment by MastaG** [comment]
Could you please try and run pli-extras/update.sh and rebuild a fresh image.
I believe I fixed it.. but not sure.

**Comment by lprot** [comment]
If you do:
```
cd build ; source env.source ; MACHINE=dm800 bitbake openpli-enigma2-image
```

It builds pli-extras-enigma2-image insted of homebuild image as it was before :(

**Comment by persianpros** [comment]
It's not a problem, there will be no more "homebuild" name as we want to know the image is ours.

**Comment by lprot** [comment]
But this way you can't distinguish this two builds:
```
cd build ; source env.source ; MACHINE=spark bitbake openpli-enigma2-image
cd build ; source env.source ; MACHINE=spark bitbake pli-extras-enigma2-image
``

**Comment by lprot** [comment]
This builds the same openpli-enigma2-pli-extras-spark_usb.zip so something is definitely happened...

**Comment by persianpros** [comment]
It's true, I don't get what's the problem.

**Comment by MastaG** [comment]
@audi06
Please run pli-extras/update.sh and rebuild.
It should be fully working now.

Please see: https://github.com/PLi-metas/pli-extras/issues/39
