### ISSUE TITLE
wrong libc headers path for spark7162 target

### ISSUE THREAD

**Issue by lprot** [PLi-metas/meta-fulan#3]
For fulan 
https://github.com/PLi-metas/meta-fulan/blob/ea1618219f6c4b320ddfc629eb1150f3d89d8f3c/recipes-bsp/linux/linux-libc-headers.inc#L7

Should contain 2.6 instead of 3.0 because libc headers can't be fetched

**Comment by MastaG** [comment]
thank you!
https://github.com/PLi-metas/meta-fulan/commit/41c36cabafcd5cda64f5b1743c524b6e48a169fe
